server:
    port: 8080

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/myApp?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName:
        username: root
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        #database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        #openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy #org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            #hibernate.cache.use_second_level_cache: true
            #hibernate.cache.use_query_cache: false
            #hibernate.generate_statistics: true


metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: mysql

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

swagger:
    title: MyApp API
    description: AngularJS app with REST backend
    version: 0.0.1
