package tb.angularjs.users.model;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


@Entity
@Inheritance
@DiscriminatorColumn(name = "user_type")
@Table(name = "users")
public abstract class User {

  // ==============
  // PRIVATE FIELDS
  // ==============
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user email
  @NotNull
  private String email;
  
  // ==============
  // PUBLIC METHODS
  // ==============
  
  /**
   * @return the id
   */
  public long getId() {
    return id;
  }

  /**
   * @return the email
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param id the id to set
   */
  public void setId(long id) {
    this.id = id;
  }

  /**
   * @param email the email to set
   */
  public void setEmail(String email) {
    this.email = email;
  }

} // class User
